name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  cleanup-old-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to delete workflow runs
      contents: read # Required to read the repository contents
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 5 # Delete runs older than 5 days
          keep_minimum_runs: 5 # Keep at least 5 runs